force-app/main/default/objects/Custom_Channel__c/Custom_Channel__c.object-meta.xml
<CustomObject>
    <label>Custom Channel</label>
    <nameField>
        <label>Channel Label</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Custom Channels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Custom_Channel__c/fields/Channel_Id__c.field-meta.xml
<CustomField>
    <fullName>Channel_Id__c</fullName>
    <label>Channel Id</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Custom_Channel__c/fields/Channel_Name__c.field-meta.xml
<CustomField>
    <fullName>Channel_Name__c</fullName>
    <description
  >Add the channel name which will publish the event to external system</description>
    <inlineHelpText
  >Custom Channel name will be subscribed to external system</inlineHelpText>
    <label>Channel Name</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Custom_Channel__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <inlineHelpText>data - Change Data Capture channel corresponding to the selected entities.
event - A channel that contains platform events.</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Data</fullName>
                <default>true</default>
                <label>Data</label>
            </value>
            <value>
                <fullName>Event</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CustomChannelController.cls
public with sharing class CustomChannelController {
	@AuraEnabled
	public static String createCustomChannel(Map<String, String> channelProps) {
		System.debug('channelProps ------- ');
		System.debug(channelProps);
		Custom_Channel__c channel = new Custom_Channel__c();
		channel.Name = channelProps.get('label');
		channel.Channel_Name__c = channelProps.get('name') + '__chn';
		channel.Type__c = channelProps.get('type');

		if (Schema.sObjectType.Custom_Channel__c.isCreateable()) {
			insert channel;
		}
		createCustomChannel(channel.Id);

		return channel.Id;
	}

	@future(callout=true)
	public static void createCustomChannel(String channelId) {
		Custom_Channel__c channel = CustomChannelService.getCustomChannel(new List<String>{ channelId })[0];
		String platformChannelId = CustomChannelService.createCustomChannel(channel);

		if (String.isNotBlank(platformChannelId)) {
			channel.Channel_Id__c = platformChannelId;
			if (Schema.sObjectType.Custom_Channel__c.isUpdateable()) {
				update channel;
			}
		}
	}
}