force-app/main/default/objects/Custom_Channel__c/Custom_Channel__c.object-meta.xml
<CustomObject>
    <label>Custom Channel</label>
    <nameField>
        <label>Channel Label</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Custom Channels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Custom_Channel__c/fields/Channel_Id__c.field-meta.xml
<CustomField>
    <fullName>Channel_Id__c</fullName>
    <label>Channel Id</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Custom_Channel__c/fields/Channel_Name__c.field-meta.xml
<CustomField>
    <fullName>Channel_Name__c</fullName>
    <description
  >Add the channel name which will publish the event to external system</description>
    <inlineHelpText
  >Custom Channel name will be subscribed to external system</inlineHelpText>
    <label>Channel Name</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Custom_Channel__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <inlineHelpText>data - Change Data Capture channel corresponding to the selected entities.
event - A channel that contains platform events.</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Data</fullName>
                <default>true</default>
                <label>Data</label>
            </value>
            <value>
                <fullName>Event</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CustomChannelService.cls
public class CustomChannelService {
  //Check Channel Exist or not
  public static String isChannelExist(String chnName) {
    String query =
      'SELECT Id,fullname FROM PlatformEventChannel where developerName=\'' +
      chnName +
      '\'';

    RestService callout = new RestService(
        Constant.baseURL + Constant.toolingQueryURL + query.replace(' ', '+')
      )
      .setHeaders(Constant.defaultHeaders)
      .setTimeout(60000);
    String response = callout.get().getBody();
    Map<string, object> fileInfos = (Map<string, object>) JSON.deserializeUntyped(
      response
    );
    if (fileInfos.containsKey('records')) {
      List<Object> stIds = (List<Object>) fileInfos.get('records');

      for (Object objLabel : stIds) {
        Map<String, Object> label = (Map<String, Object>) objLabel;
        if (label.get('Id') != null) {
          return String.valueof(label.get('Id'));
        } else {
          return null;
        }
      }
    }
    return null;
  }

  //Create Custom Channel
  public static String createCustomchannel(Custom_Channel__c customChannel) {
    RestService callout = new RestService(
        Constant.baseURL + Constant.toolingsObjectURL + 'PlatformEventChannel'
      )
      .setHeaders(Constant.defaultHeaders)
      .setTimeout(60000);

    Map<string, object> innerType = new Map<string, object>();
    innerType.put('channelType', customChannel.Type__c);
    innerType.put('label', customChannel.Name);
    Map<string, object> channelBody = new Map<string, object>();
    // parmeter channel name
    channelBody.put('FullName', customChannel.Channel_Name__c);
    channelBody.put('Metadata', innerType);

    String response = callout.post(channelBody).getBody();
    System.debug(response);
    Map<string, object> fileInfos = (Map<string, object>) JSON.deserializeUntyped(
      response
    );
System.debug(fileInfos);
    String channelId;
    if (fileInfos.containsKey('id')) {
      channelId = String.valueof(fileInfos.get('id'));
    }
    return channelId;
  }

  public static List<Custom_Channel__c> getCustomChannel(
    List<String> channelIds
  ) {
    return [
      SELECT Id, Name, Channel_Name__c, Type__c, Channel_Id__c
      FROM Custom_Channel__c
      WHERE Id IN :channelIds
    ];
  }
}