force-app/main/default/objects/Channel_Member__c/Channel_Member__c.object-meta.xml
<CustomObject>
    <label>Channel Member</label>
    <nameField>
        <displayFormat>CMN-{0000000}</displayFormat>
        <label>Channel Member Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Channel Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Channel_Member__c/fields/Add_to_Channel__c.field-meta.xml
<CustomField>
    <fullName>Add_to_Channel__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Add to Channel</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Channel_Member__c/fields/Custom_Channel__c.field-meta.xml
<CustomField>
    <fullName>Custom_Channel__c</fullName>
    <label>Custom Channel</label>
    <referenceTo>Custom_Channel__c</referenceTo>
    <relationshipLabel>Channel Members</relationshipLabel>
    <relationshipName>Channel_Members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Channel_Member__c/fields/Enriched_Fields__c.field-meta.xml
<CustomField>
    <fullName>Enriched_Fields__c</fullName>
    <inlineHelpText
  >Add the field API Names comma separated without space with maximum 10 fields</inlineHelpText>
    <label>Enriched Fields</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Channel_Member__c/fields/Filter_Expression__c.field-meta.xml
<CustomField>
    <fullName>Filter_Expression__c</fullName>
    <label>Filter Expression</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Channel_Member__c/fields/Object_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_API_Name__c</fullName>
    <label>Object API Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Channel_Member__c/fields/Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_Name__c</fullName>
    <label>Object Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Custom_Channel__c/Custom_Channel__c.object-meta.xml
<CustomObject>
    <label>Custom Channel</label>
    <nameField>
        <label>Channel Label</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Custom Channels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/AddPlatformMemberScreenController.cls
public with sharing class AddPlatformMemberScreenController {
  @AuraEnabled(cacheable=true)
  public static UtilDTO.DualListDTO getInitialDetails(String recordId) {
    UtilDTO.DualListDTO dualDTO = new UtilDTO.DualListDTO();
    try {
      dualDTO.customChannel = CustomChannelService.getCustomChannel(new List<String>{recordId})[0];
      dualDTO.selectedOption = getSelectedObjectsFromRecord(recordId);
      dualDTO.options = getCDCEnabledObjects();
    } catch (Exception e) {
      throw new AuraHandledException(e.getMessage());
    }
    return dualDTO;
  }

  // Method to get optionDTO of CDC enabled Objects
  private static List<UtilDTO.OptionDTO> getCDCEnabledObjects() {
    List<UtilDTO.OptionDTO> objectOptions = new List<UtilDTO.OptionDTO>();
    for (Schema.SObjectType obj : filterCDCEnabledObjects().values()) {
      // Get the object describe to show label
      Schema.DescribeSObjectResult describe = obj.getDescribe();
      String optionValue = describe.getName();
      String optionLabel =
        describe.getLabel() +
        ' (' +
        describe.getName() +
        ')';
      objectOptions.add(new UtilDTO.OptionDTO(optionLabel, optionValue));
    }
    objectOptions.sort();
    return objectOptions;
  }

  private static Map<String, Schema.SObjectType> filterCDCEnabledObjects() {
    Map<String, Schema.SObjectType> cdcObjects = new Map<String, Schema.SObjectType>();

    // Get all global describe
    Map<String, Schema.SObjectType> globalDescribe = Schema.getGlobalDescribe();

    // Iterate through all objects
    for (String objName : globalDescribe.keySet()) {
      // Check if the object name ends with 'ChangeEvent'
      if (objName.toLowerCase().endsWith('changeevent')) {
        // Remove 'ChangeEvent' suffix to get the original object name
        String originalObjName = objName.toLowerCase()
          .replace('__changeevent', '__c')
          .removeEnd('changeevent');
        cdcObjects.put(originalObjName, globalDescribe.get(originalObjName));
      }
    }

    return cdcObjects;
  }

  private static List<String> getSelectedObjectsFromRecord(String recordId) {
    List<String> selectedObjects = new List<String>();
    for (Channel_Member__c cMember : [
      SELECT
        Id,
        Enriched_Fields__c,
        Filter_Expression__c,
        Object_Name__c,
        Object_API_Name__c
      FROM Channel_Member__c
      WHERE Custom_Channel__c = :recordId AND Add_to_Channel__c = true WITH SECURITY_ENFORCED
    ]) {
      selectedObjects.add(cMember.Object_API_Name__c);
    }
    return selectedObjects;
  }

  @AuraEnabled
  public static void createChannelMember(){
    try {
      
    } catch (Exception e) {
      throw new AuraHandledException(e.getMessage());
    }
  }
}